- nnoir-chainer/nnoir_chainer/configuration.py
Fix error message which uses wrong module name.
> Fix module name from chainer.nnoir to nnoir_chainer

- nnoir-chainer/README.md
ClippedReLU seems to be supported but not on the list.
> Add ClippedReLU

- nnoir-onnx/freeze_onnx
- nnoir-onnx/nnoir_onnx/onnx.py
- nnoir-onnx/setup.py
This PR includes the follows:
- `onnx2nnoior` will aborts if [dimension variables](https://github.com/onnx/onnx/blob/master/docs/IR.md) are included in ONNX files
- append `freeze_onnx` script to assign the actual integers to dimension variables 
```
$ freeze_onnx freeze -o freezed_model.onnx --fix-dimension H=1,W=2 Model.onnx 
```
```
$ freeze_onnx list Model.onnx
{'H', 'W'}
```
> Append `freeze_onnx` to assignment to dimension variables

- nnoir-onnx/nnoir_onnx/onnx.py
- nnoir/nnoir/nnoir.py
Initializer name is not restricted to C identifier syntax rule. (Why?)
see https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph
> nnoir-onnx: rename initializer name.

- nnoir-onnx/setup.py
Fix onnx version.
This is due to incompatible between `onnx` and `onnxruntime`.
Currently, `onnxruntime` does not support `ir_version = 7` and `opset version = 12` (provided since `onnx 1.7.0`).
This makes all tests of `nnoir-onnx` will fail.
> Fix onnx version (temporary)

- nnoir-onnx/setup.py
Thanks to the update of `onnxruntime`, opset 12 can be tested.
Then, we can remove version restriction.
https://github.com/Microsoft/onnxruntime/releases/tag/v1.3.0
> nnoir-onnx: remove version restriction

- .circleci/config.yml
- nnoir-onnx/test/test_average_pooling_2d.py
- nnoir-onnx/test/test_concat.py
- nnoir-onnx/test/test_dropout.py
- nnoir-onnx/test/test_elu.py
- nnoir-onnx/test/test_flatten.py
- nnoir-onnx/test/test_gemm.py
- nnoir-onnx/test/test_lrn.py
- nnoir-onnx/test/test_matmul.py
- nnoir-onnx/test/test_max_pooling.py
- nnoir-onnx/test/test_mul.py
- Replace nosetests with pytest
- Currently, printing test names are difficult to see in `nnoir-onnx`. (nosetests use comments like "opset version > ...")
pytest give us finer controls.
- Development of pytest is more active.
- Split  all test into usual tests and chainer related component test for speed-up testing.
> Use pytest && split tests into `test` and `test-chainer-component`

- nnoir-onnx/nnoir_onnx/operators/clip.py
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip
So, onnx2nnoir must convert it to a scalar.
> keras2onnx pass tensors of non-empty shape to clip

- .circleci/config.yml
Add auth information for pulling docker executor images to avoid Docker Hub's anonymous pull limitation.
cf. https://circleci.com/docs/2.0/private-images/
```
Hi there,
On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
We are currently working …
```
> avoid Docker Hub rate limits

- nnoir-onnx/freeze_onnx
- nnoir-onnx/nnoir_onnx/__init__.py
- nnoir-onnx/nnoir_onnx/utils.py
- nnoir-onnx/onnx2nnoir
Deal with #72.
The following error is displayed.
```
% onnx2nnoir -o example/super_resolution/super_resolution.nnoir example/super_resolution/super_resolution/super_resolution.onnx
Error: This ONNX model includes dimension variables.
{'batch_size'}
Set the values with `freeze_onnx freeze`.
$ freeze_onnx freeze --help
```
> Check shape in onnx2nnoir

- .circleci/config.yml
- nnoir-onnx/example/.gitignore
- nnoir-onnx/example/super_resolution/Makefile
- nnoir-onnx/nnoir_onnx/onnx.py
- nnoir-onnx/onnx2nnoir
```
% ./onnx2nnoir -o example/super_resolution/super_resolution.nnoir tmp/super_resolution_fixed.onnx
Error: graph name "torch-jit-export" is not C identifier.
see https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph.
You can override the graph name with the `--graph_name` option.
% ./onnx2nnoir -o example/super_resolution/super_resolution.nnoir --graph_name torch_jit_export tmp/super_resolution_fixed.onnx
2020-11-06 11:30:49.197308735 [W:onnxruntime:, graph.cc:814 Graph] Initializer conv1.bias appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with …
```
> Add --graph_name option

- nnoir-onnx/example/super_resolution/Makefile
- nnoir-onnx/freeze_onnx
- nnoir-onnx/nnoir_onnx/onnx.py
- nnoir-onnx/nnoir_onnx/utils.py
- nnoir-onnx/onnx2nnoir
```
% onnx2nnoir -o super_resolution.nnoir --graph_name torch_jit_export super_resolution.onnx
Error: This ONNX model includes dimension variables.
{'batch_size'}
Set the values with the `--fix_dimension` option.
% onnx2nnoir -o super_resolution.nnoir --graph_name torch_jit_export --fix_dimension batch_size=1 super_resolution.onnx
2020-11-06 13:11:36.945196840 [W:onnxruntime:, graph.cc:814 Graph] Initializer conv1.bias appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-11-06 13:11:36.947018295 …
```
> Add --fix_dimension option

- .circleci/config.yml
fix [this](https://app.circleci.com/pipelines/github/Idein/nnoir/311/workflows/05dc97a5-f45c-44c9-b88e-f84c28cf7a6c/jobs/363)
```
InvalidConfiguration: Missing 'pypitest' section from the configuration file
or not a complete URL in --repository-url.
Maybe you have an out-dated '~/.pypirc' format?
more info: https://packaging.python.org/specifications/pypirc/
```
> twine requires url to upload pypitest package index

- nnoir/nnoir/functions/batch_normalization.py
fix the following error:
```
File "/usr/local/lib/python3.7/dist-packages/nnoir/functions/batch_normalization.py", line 16, in run
shape = (1, self.params['gamma'].size) + ((1,) * (len(x.shape) - 2))
AttributeError: 'NoneType' object has no attribute 'size'
```
> Fix run of batch_normalization

- nnoir-onnx/nnoir_onnx/operators/div.py
My PR #111 is implmete for 0-dimensional ndarray.
This PR fix that.
> fix bug when the second input of `Div` is 0-dimensional ndarray

- nnoir-onnx/nnoir_onnx/onnx.py
If the onnx graph name is a C keyword, `--graph_name` option is not suggested as the error occurs in nnoir library.
In this fix onnx2nnoir generate error and suggest `--graph_name` option if the onnx graph name is a C keyword.
"main" is a valid C identifier, but it may conflict with main function of C in practice.
In this fix onnx2nnoir show warning and suggest `--graph_name` option  if the onnx graph name is "main".
> Validate graph name

- nnoir-onnx/nnoir_onnx/operators/pad.py
- nnoir-onnx/test/test_pad.py
The value of Pad in nnoir must be scalar.
Fix 0-dimension ndarray to scalar in onnx2nnoir.
> Fix bug of Pad

- nnoir/nnoir/functions/linear.py
Linear.run() with 8bit weight, implemented in #117, was wrong.
> bugfix: linear.run with uint8 weight

- nnoir/nnoir/nnoir.py
> nnoir: explicitly collect unreachable resources

- nnoir-onnx/nnoir_onnx/onnx.py
- not to search nodes with empty name, as an optional input for nodes may have empty name.
> skip input without name

- .circleci/config.yml
Directly use pypi tokens when  `poetry publish` to workaround the following token error. 
```
#!/bin/bash -eo pipefail
poetry publish --build --username "__token__" --password "$PYPI_TOKEN" --no-interaction
Building nnoir (1.0.9)
- Building sdist
- Built nnoir-1.0.9.tar.gz
- Building wheel
- Built nnoir-1.0.9-py3-none-any.whl
Publishing nnoir (1.0.9) to PyPI
- Uploading nnoir-1.0.9-py3-none-any.whl 0% - Uploading nnoir-1.0.9-py3-none-any.whl 100% - Uploading nnoir-1.0.9-py3-none-any.whl 100%
UploadError
HTTP Error 403: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/publishing/uploader.py:216 in _upload
212│                     self._register(session, url) …
```
> expand release job

- nnoir/README.md
- nnoir/nnoir/load.py
- nnoir/nnoir/metadata.py
- nnoir/nnoir/nnoir.py
- nnoir/pyproject.toml
```bash
$ nnoir-metadata resnet_50.nnoir
name = CaffeFunction
description =
generator.name = chainer
generator.version = 7.7.0
$ nnoir-metadata resnet_50.nnoir --write-description "This is resnet_50 (written by nnoir-metada)"
$ nnoir-metadata resnet_50.nnoir                                            
name = CaffeFunction
description = This is resnet_50 (written by nnoir-metada)
generator.name = chainer
generator.version = 7.7.0
$ nnoir-metadata resnet_50.nnoir --write-name "CaffeFunction_V2"
$ nnoir-metadata resnet_50.nnoir
name = CaffeFunction_V2
description = This is resnet_50 (written by nnoir-metada)
generator.name = chainer
generator.version = 7.7.0
```
> `nnoir-metadata`: script for read/write nnoir metadata

- nnoir-onnx/nnoir_onnx/onnx.py
Fixed to check if nodes before the `Shape` node have constant.
> fix _list_constant_nodes()

- nnoir-onnx/README.md
- nnoir-onnx/nnoir_onnx/operators/slice.py
sliceの実装がopset10以降を想定したものであったため、opset9以前の場合は`UnsupportedONNXOperation`を返すようにした
> Add opset version check for slice
