.circleci/config.yml
`ubuntu:18.04` -> `python:buster`
=> replace CI base image

nnoir/nnoir/functions/batch_normalization.py, nnoir/nnoir/functions/convolution_2d.py, nnoir/nnoir/functions/linear.py, nnoir/nnoir/functions/scale.py
* convolution_2d without bias
* linear without bias
* reshape before linear
* batch_normalization shape
* scale without bias
=> nnoir: fix runtime

.circleci/config.yml, nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/add.py, nnoir-onnx/nnoir_onnx/operators/average_pool.py, nnoir-onnx/nnoir_onnx/operators/batch_normalization.py, nnoir-onnx/nnoir_onnx/operators/clip.py, nnoir-onnx/nnoir_onnx/operators/concat.py, nnoir-onnx/nnoir_onnx/operators/conv.py, nnoir-onnx/nnoir_onnx/operators/dropout.py, nnoir-onnx/nnoir_onnx/operators/gemm.py, nnoir-onnx/nnoir_onnx/operators/global_average_pool.py, nnoir-onnx/nnoir_onnx/operators/leaky_relu.py, nnoir-onnx/nnoir_onnx/operators/lrn.py, nnoir-onnx/nnoir_onnx/operators/mat_mul.py, nnoir-onnx/nnoir_onnx/operators/max_pool.py, nnoir-onnx/nnoir_onnx/operators/pad.py, nnoir-onnx/nnoir_onnx/operators/reduce_sum.py, nnoir-onnx/nnoir_onnx/operators/relu.py, nnoir-onnx/nnoir_onnx/operators/reshape.py, nnoir-onnx/nnoir_onnx/operators/resize.py, nnoir-onnx/nnoir_onnx/operators/softmax.py, nnoir-onnx/nnoir_onnx/operators/sub.py, nnoir-onnx/nnoir_onnx/operators/sum.py, nnoir-onnx/nnoir_onnx/operators/tanh.py, nnoir-onnx/nnoir_onnx/operators/transpose.py, nnoir-onnx/nnoir_onnx/operators/utils.py
In nnoir, array shape is known information.
=> nnoir-onnx: ONNX Shape operator is nnoir constant

nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/flatten.py
Adds support of the Flatten operator. 
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Flatten
=> add support to Flatten

nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/elu.py
Adds support of Elu operator of ONNX in nnoir-onnx. (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Elu)
=> add support of elu operator

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/resize.py
- fix Resize operator support
- add check for opset version if Resize op is used
- update README with supported operators
=> update readme and fix Resize op for nnoir-onnx

nnoir-chainer/nnoir_chainer/functions/array/concat.py, nnoir-chainer/nnoir_chainer/functions/normalization/local_response_normalization.py, nnoir-onnx/nnoir_onnx/operators/concat.py, nnoir-onnx/setup.py
* fix `LRN` param types
* convert `Concat` axis natural number
=> Fix parameter type and range

nnoir-onnx/nnoir_onnx/onnx.py
This PR generates internal value_infos ourselves
=> nnoir-onnx: remove `infer_shapes` which don't restore value_info

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/prelu.py
This PR append the support for `PRelu`.
See `Readme.md` to know the restriction.
=> nnoir-onnx: Support PRelu

nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/setup.py
=> nnoir-onnx: reduce memory usage (fix #38)

nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/resize.py
Performs check inside each operator class, instead of top level.
(follows Clip operator)
=> uniformize opset check

nnoir-chainer/nnoir_chainer/graph.py, nnoir-chainer/test/test_concat.py, nnoir/nnoir2dot
Like this `F.concat([h,h], axis=1)`.
=> Support function with inputs reference same value

nnoir-onnx/nnoir_onnx/operators/max_pool.py, nnoir-onnx/test/test_max_pooling.py
=> fix ceil_mode check for max_pool

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/reduce_mean.py, nnoir-onnx/nnoir_onnx/operators/utils.py, nnoir-onnx/test/test_reduce_mean.py, nnoir-onnx/test/test_reduce_sum.py
ReduceMean -> Sum+MulConstant(1/n)
=> nnoir-onnx: ReduceMean

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/unsqueeze.py, nnoir-onnx/test/test_unsqueeze.py
=> nnoir-onnx: Unsqueeze

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/mul.py, nnoir-onnx/nnoir_onnx/operators/utils.py, nnoir-onnx/test/test_mul.py
=> Adds ONNX Mul op

nnoir-onnx/nnoir_onnx/operators/add.py, nnoir-onnx/test/test_add.py
Support of mulitdirectional broadcasting for Add operator (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Add)
=> nnoir-onnx: Add op with support of multidirectional broadcast

nnoir-chainer/setup.py, nnoir-onnx/setup.py, nnoir/nnoir/load.py, nnoir/nnoir/nnoir.py, nnoir/setup.py
Deal with https://pypi.org/project/msgpack-python/.
Stay compatiblity with the old format. (ref: https://pypi.org/project/msgpack/)
=> Update msgpack-python to msgpack

nnoir-onnx/nnoir_onnx/operators/gemm.py, nnoir-onnx/test/test_gemm.py
=> Improve to_function in OpGemm

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/mat_mul.py, nnoir-onnx/test/test_matmul.py
=> Improve to_function in OpMatMul

nnoir/nnoir2dot
=> Fix nnoir2dot

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/squeeze.py, nnoir-onnx/test/test_squeeze.py
Support [Squeeze](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze)
=> Add squeeze to nnoir-onnx

nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/lstm.py
- Fix the shape of internal node in LSTM
- Fix generating invalid graphs when the number of outputs are greater than 2
=> Fix bugs in LSTM

nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/gemm.py, nnoir-onnx/nnoir_onnx/operators/max_pool.py, nnoir-onnx/nnoir_onnx/operators/pad.py, nnoir-onnx/nnoir_onnx/operators/resize.py, nnoir-onnx/nnoir_onnx/operators/utils.py, nnoir-onnx/onnx2nnoir
- remove `check_graph`
- catch runtime error in `onnx2nnoir`
=> Refactoring check_graph

nnoir-onnx/test/test_clip.py, nnoir-onnx/test/test_reduce_sum.py, nnoir-onnx/test/test_squeeze.py, nnoir-onnx/test/test_unsqueeze.py
=> Fix nnoir-onnx test provisionally

.circleci/config.yml
=> Add nightly test

.circleci/config.yml
release packages from CI by tagging like `nnoir(-*)-[version]`
=> Release from CI

nnoir-onnx/nnoir_onnx/operators/reduce_sum.py, nnoir-onnx/nnoir_onnx/operators/squeeze.py, nnoir-onnx/nnoir_onnx/operators/unsqueeze.py, nnoir-onnx/test/test_reduce_sum.py, nnoir-onnx/test/test_squeeze.py, nnoir-onnx/test/test_unsqueeze.py
=> Support Opset 13

.circleci/config.yml
at https://github.com/Idein/nnoir/pull/90
=> forget to install twine

.circleci/config.yml
=> add pypi API token for each package

nnoir/nnoir/__init__.py, nnoir/nnoir/nntc.py, nnoir/nnrunner, nnoir/setup.py
=> Add nnrunner

nnoir/nnoir/nnoir.py
=> Fix type of outputs in nntc

.circleci/config.yml, blackonnx/setup.py, nnoir-onnx/nnoir_onnx/operators/div.py, nnoir-onnx/setup.py, nnoir-onnx/test/test_div.py
Fix bug of division.
When we have`Div(a, b)` and 
- a is not constant
- b is constant
then the test case will failed.
----
Ci failed due to
- black (due to pysen)
- onnx
I append the version restriction)
=> Fix bug of Div

blackonnx/setup.py, nnoir-onnx/setup.py
Due to release onnxruntime 1.8.
=> Update onnx version

nnoir/nnoir/functions/convolution_2d.py, nnoir/nnoir/functions/depthwise_convolution_2d.py, nnoir/nnoir/functions/linear.py, nnoir/nnoir/functions/scale.py, nnoir/nnoir/functions/util.py
Add parameter for 8bit quantization for gemm-like functions.
In `run` functions it is assumed that nnoir files are quantized by [google's gemmlowp](https://github.com/google/gemmlowp/blob/master/doc/quantization.md).
=> 8bit quantization

nnoir-onnx/nnoir_onnx/onnx.py
- Suppress onnxruntime warnings
- Improve error message
=> Improve onnx2nnoir

nnoir/poetry.lock, nnoir/pyproject.toml
- https://github.com/Idein/nnoir/pull/129
- https://github.com/Idein/nnoir/pull/130
- https://github.com/Idein/nnoir/pull/133
=> Bump version nnoir 1.0.9

nnoir-onnx/poetry.lock, nnoir-onnx/pyproject.toml
- #129 
- #131
-  #133
-  #137
=> bump version nnoir-onnx-1.0.15

nnoir-onnx/poetry.lock, nnoir-onnx/pyproject.toml
- https://github.com/Idein/nnoir/pull/150
=> bump version nnoir-onnx-1.0.16

nnoir-onnx/README.md, nnoir-onnx/poetry.lock, nnoir-onnx/pyproject.toml
=> Bump version nnoir onnx 1.0.17

nnoir/poetry.lock, nnoir/pyproject.toml
- https://github.com/Idein/nnoir/pull/156
=> nnoir v1.1.0

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/onnx.py, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/hard_swish.py, nnoir-onnx/test/test_hard_swish.py
enable onnx2nnoir to convert [HardSwish](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hardswish)
=> onnx2nnoir: add hard_swish

nnoir-onnx/README.md, nnoir-onnx/poetry.lock, nnoir-onnx/pyproject.toml
- https://github.com/Idein/nnoir/pull/170
- https://github.com/Idein/nnoir/pull/158
=> nnoir-onnx 1.1.0

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/hard_sigmoid.py, nnoir-onnx/test/test_hard_sigmoid.py
enable onnx2nnoir to convert [HardSigmoid](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hardsigmoid)
=> [DODO-274] onnx2nnoir: add hard_sigmoid

nnoir-onnx/README.md, nnoir-onnx/pyproject.toml
- https://github.com/Idein/nnoir/pull/181
=> nnoir-onnx 1.2.0

nnoir-onnx/nnoir_onnx/operators/hard_sigmoid.py
=> Fix HardSigmoid

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/split.py, nnoir-onnx/test/test_split.py
Removes the restrictions on Split opset version and operands
=> Enhance Split support in onnx2nnoir

nnoir-onnx/example/super_resolution/Makefile
onnxのmodel zooのほうで変更があったため対応
https://github.com/onnx/models/pull/636
=> Fix url in example/super_resolution/Makefile

nnoir-onnx/README.md, nnoir-onnx/example/super_resolution/Makefile, nnoir-onnx/nnoir_onnx/operators/__init__.py, nnoir-onnx/nnoir_onnx/operators/pow.py, nnoir-onnx/test/test_pow.py
- Add pow operator to nnoir-onnx operators.
- Add test for pow operator.
- Add [Pow] line to README.
=> Add pow operator

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/sub.py, nnoir-onnx/test/test_sub.py
- Change sub in nnoir-onnx to handle 1st constant.
- Add test.
- Remove 1 sentence from README.
=> Add 1st constant handler to sub.

nnoir-onnx/README.md, nnoir-onnx/nnoir_onnx/operators/max_pool.py, nnoir-onnx/test/test_max_pooling.py
- Change maxpool in nnoir-onnx to handle dilations if this parameter is array of 1.
- Add test.
- Change 1 sentence in README.
=> Change maxpool to handle dilations if it is array of 1.

nnoir-onnx/nnoir_onnx/operators/softmax.py
- Change default value check for axis param.
- Add negative value check for axis param.
=> Fix softmax operator in onnx2nnoir
